### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by toofan0909** [deepgram/deepgram-brain-python#2]
```
from deepgram import Brain

# Get your user_id and token from deepgram.com/console/documentation
brainAPI = Brain(user_id='cxcxcxcxcxcxcxcxcxc', token='xcxcxcxcxcxcxcxcxxc')

audioFileLocation = 'my_thoughts_2017_10_25_nlp_lessons_001.wav'

with open(audioFileLocation, mode='rb') as audioFile:
    asset = brainAPI.transcribe(audioFile)
  
print asset
```

I getting following error 

  File "test.py", line 40, in <module>
    asset = brainAPI.transcribe(audioFile)
  File "C:\Python27\lib\site-packages\deepgram\connection.py", line 138, in tran
scribe
    return self.uploadAsset(data, async=False)['transcript']
  File "C:\Python27\lib\site-packages\deepgram\connection.py", line 124, in uplo
adAsset
    assert isinstance(data, bytes)
AssertionError

please guide ...

**Comment by ajsyp** [comment]
The package was built for Python 3. It looks like you're using Python 2.7. Can you try Python and let us know how it goes?

**Comment by toofan0909** [comment]
Hello

Many thanks for the response,  ..... good news and bad news ...

.it works with python 3.

I would have to upgrade my multi-threaded application to  python 3... (even to test the use cases), this is huge effort.

any tips on how can i port it back to python 2.7?

regards

**Comment by greedyuser** [comment]
I think that we need to reconsider the python 2.7 target. We will discuss internally and get back with you.

**Comment by greedyuser** [comment]
After digging more I think this error may be due to a non-byte array being sent in, like a numpy array. Are you sending in an array from something like scipy.io.wavefile.read()? If so, even if you run .tobytes() the call will fail since it isn't a valid audio file (at a minimum we would need rate information to process it). Try something like:

     import tempfile
     from scipy.io import wavefile as wav 
     with tempfile.TemporaryFile() as wavFile:
          wav.write(wavFile, rate, data)
          wavFile.seek(0)
          wavData = wavFile.read()
          newAsset = brainAPI.uploadAsset(wavData,metadata={'filename':'some name})

**Comment by toofan0909** [comment]
Hello ... 

Tonight I will try your suggestion, just for my reference what's in 

"import tempfile
from scipy.io import wavefile as wav "
--------------------------------------------------
update from today's test run ... 
result : no progress with python 2.7 

    if isinstance(data, io.BufferedReader):
      data = data.read()
    print data
    assert isinstance(data, bytes)
>> here is the output of this print ... 

<open file 'audioTest.wav', mode 'rb' at 0x027F4B20>

--------------------------------------------------- 
same program works like charm on python 3 installation .. I am just trying to understand whats the difference,, 

please guide, for u guys it might be 2 hour job, but for a end user like me it is a mess, I don't want to upgrade my whole application to python 3

**Comment by greedyuser** [comment]
Ok, so for python 2.X a file is not an instance of bufferedreader. To make your code work just add '.read()' in the call. So, something like:

    from deepgram import Brain

    TEST_FILE = 'somefile.wav'

    def main():
      brainAPI = Brain(user_id='<USER_ID>', token='<TOKEN>')
      with open(TEST_FILE, mode='rb') as audioFile:
        asset = brainAPI.uploadAsset(audioFile.read(), metadata={'filename': TEST_FILE})

      print(brainAPI.asset(asset['asset_id'])['transcript'])

    if __name__ == '__main__':
      main()
